### ISSUE TITLE
[Feature] Validate anchors

### ISSUE THREAD

**Issue by rmartine-ias** [theoludwig/markdownlint-rule-relative-links#2]
## Description

It would be very useful to validate that anchors exist:

`some.md`:

```markdown
[Link](other.md#existing)
[Link](other.md#not-existing)
```

`other.md`:

```markdown
# Existing
```

This would give an error that `other.md#not-existing` is not a valid link.

This would be useful, because I moved a section from one file to another, and now I don't know what links I've broken. Similarly, I would like to know when renaming a header invalidates a link.

## Describe the solution you'd like

A piece of config to specify whether to opt-out of this behavior, with it being on by default.

## Describe alternatives you've considered

I considered switching to markdownlint-link-check, but they [don't do it](https://github.com/tcort/markdown-link-check/issues/212) either.

The other alternative would be the current behavior, not linting for dead link fragments.

**Comment by theoludwig** [comment]
Hello! :wave: @rmartine-ias 

Thanks for your report.
Validating anchors/fragments in other files is a great idea!
[markdownlint](https://github.com/DavidAnson/markdownlint) already validate fragments with the [MD051 - `link-fragments`](https://github.com/DavidAnson/markdownlint/blob/main/doc/md051.md) rule, but is only working for titles in the same file.
Could be great to make it work with links to other files, with a similar logic for converting headings/titles to fragments as the MD051 rule in markdownlint (https://github.com/DavidAnson/markdownlint/blob/d01180ec5a014083ee9d574b693a8d7fbc1e566d/lib/md051.js#L19).

Feel free to open PRs to implement this feature, would appreciate it. :smile:

**Comment by rmartine-ias** [comment]
Thank you so much for implementing this! Was unable to get around to doing it myself, this will be super useful.
